<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE lingvoj [

<!ELEMENT lingvoj (lingvo)*>
<!ELEMENT lingvo (#PCDATA)>
<!ATTLIST lingvo kodo ID #REQUIRED
                 flago CDATA #IMPLIED>
]>

<!-- vd. i.a. https://de.wikipedia.org/wiki/Modul:Language/data/iana_languages
  https://de.wikipedia.org/wiki/%C3%9Cberblicksliste_der_ISO-639-3-Codes
-->


<lingvoj>
  <lingvo kodo="ab">abĥaza</lingvo>
  <lingvo kodo="ace">aĉea</lingvo>
  <lingvo kodo="af">afrikansa</lingvo>
  <lingvo kodo="ak">akana</lingvo>
  <lingvo kodo="am">amhara</lingvo>
  <lingvo kodo="an">aragona</lingvo>
  <lingvo kodo="ang">malnovangla</lingvo>
  <lingvo kodo="ar">araba</lingvo>
  <lingvo kodo="as">asama</lingvo>
  <!-- lingvo kodo="ase">uson-signolingva</lingvo -->
  <lingvo kodo="ay">ajmara</lingvo>
  <lingvo kodo="az">azerbajĝana</lingvo>
  <lingvo kodo="ba">baŝkira</lingvo>
  <lingvo kodo="be">belorusa</lingvo>
  <!-- lingvo kodo="bfi">brit-signolingva</lingvo -->
  <lingvo kodo="bg">bulgara</lingvo>
  <lingvo kodo="bh">bihara</lingvo>
  <lingvo kodo="bi">bislama</lingvo>
  <lingvo kodo="bn">bengala</lingvo>
  <lingvo kodo="bo">tibeta</lingvo>
  <lingvo kodo="br">bretona</lingvo>
  <lingvo kodo="bs">bosna</lingvo>
  <lingvo kodo="ca">kataluna</lingvo>
  <lingvo kodo="cmn">mandarena</lingvo>
  <lingvo kodo="co">korsika</lingvo>
  <lingvo kodo="cs">ĉeĥa</lingvo>
  <lingvo kodo="cv">ĉuvaŝa</lingvo>
  <lingvo kodo="cy">kimra</lingvo>
  <lingvo kodo="da">dana</lingvo>
  <lingvo kodo="de">germana</lingvo>
  <lingvo kodo="dsb">malsupra-soraba</lingvo>
  <!-- lingvo kodo="dse">nederland-signolingva</lingvo -->
  <lingvo kodo="dz">dzonka</lingvo>
  <lingvo kodo="egy">egipta</lingvo>
  <lingvo kodo="el">greka</lingvo>
  <lingvo kodo="en">angla</lingvo>
  <lingvo kodo="eo">esperanta</lingvo>
  <lingvo kodo="es">hispana</lingvo>
  <lingvo kodo="et">estona</lingvo>
  <lingvo kodo="eu">eŭska</lingvo>
  <lingvo kodo="fa">persa</lingvo>
  <lingvo kodo="fi">finna</lingvo>
  <lingvo kodo="fj">fiĝia</lingvo>
  <lingvo kodo="fo">feroa</lingvo>
  <lingvo kodo="fr">franca</lingvo>
  <lingvo kodo="fur">friula</lingvo>
  <lingvo kodo="fy">okcidentfrisa</lingvo>
  <lingvo kodo="ga">irlanda</lingvo>
  <lingvo kodo="gd">skotgaela</lingvo>
  <lingvo kodo="gl">galega</lingvo>
  <lingvo kodo="gn">gvarania</lingvo>
  <lingvo kodo="goyu">tajvana</lingvo>
  <lingvo kodo="grc">malnovgreka</lingvo>
  <!-- lingvo kodo="gsg">german-signolingva</lingvo -->
  <lingvo kodo="gu">guĝarata</lingvo>
  <lingvo kodo="gv">manksa</lingvo>
  <lingvo kodo="ha">haŭsa</lingvo>
  <lingvo kodo="he">hebrea</lingvo>
  <lingvo kodo="hi">hinda</lingvo>
  <lingvo kodo="hmn">monga</lingvo>
  <lingvo kodo="hr">kroata</lingvo>
  <lingvo kodo="hsb">supra-soraba</lingvo>
  <lingvo kodo="ht">haitia</lingvo>
  <lingvo kodo="hu">hungara</lingvo>
  <lingvo kodo="hy">armena</lingvo>
  <lingvo kodo="ia">interlingvaa</lingvo>
  <lingvo kodo="id">indonezia</lingvo>
  <lingvo kodo="ie">okcidentala</lingvo>
  <lingvo kodo="ig">igba</lingvo>
  <lingvo kodo="ik">inupiaka</lingvo>
  <!-- International Sign, piĝina lingvo surbaze de i.a. Gestuno kaj usona signolingvo,
     vd. i.a. 
     - https://en.wikipedia.org/wiki/International_Sign
     - https://web.archive.org/web/20150709214710/http://www.handspeak.com/world/isl/index.php
     - http://www.sematos.eu/isl.html
     -->
  <lingvo kodo="ils">internaci-signolingva</lingvo>  
  <lingvo kodo="io">ida</lingvo>
  <lingvo kodo="is">islanda</lingvo>
  <lingvo kodo="it">itala</lingvo>
  <lingvo kodo="iu">inuktituta</lingvo>
  <lingvo kodo="ja">japana</lingvo>
  <lingvo kodo="jbo">loĵbana</lingvo>
  <lingvo kodo="jv">java</lingvo>
  <!-- lingvo kodo="jw">java</lingvo> anst. per jv -->
  <lingvo kodo="ka">kartvela</lingvo>
  <lingvo kodo="kek">kekĉia</lingvo>
  <lingvo kodo="kg">konga</lingvo>
  <lingvo kodo="kha">ĥasia</lingvo>
  <lingvo kodo="kk">kazaĥa</lingvo>
  <lingvo kodo="kl">gronlanda</lingvo>
  <lingvo kodo="km">kmera</lingvo>
  <lingvo kodo="kn">kanara</lingvo>
  <lingvo kodo="ko">korea</lingvo>
  <lingvo kodo="ks">kaŝmira</lingvo>
  <lingvo kodo="ku">kurda</lingvo>
  <lingvo kodo="ky">kirgiza</lingvo>
  <lingvo kodo="la">latineca</lingvo>
  <lingvo kodo="lat">latina</lingvo>
  <lingvo kodo="lb">luksemburga</lingvo>
  <lingvo kodo="lfn">elefena</lingvo>
  <lingvo kodo="li">limburga</lingvo>
  <lingvo kodo="liv">livona</lingvo>
  <lingvo kodo="lld">ladina</lingvo>
  <lingvo kodo="ln">lingala</lingvo>
  <lingvo kodo="lo">laŭa</lingvo>
  <lingvo kodo="lt">litova</lingvo>
  <lingvo kodo="lu">luba</lingvo>
  <lingvo kodo="lv">latva</lingvo>
  <lingvo kodo="mg">malagasa</lingvo>
  <lingvo kodo="mi">maoria</lingvo>
  <lingvo kodo="mk">makedona</lingvo>
  <lingvo kodo="ml">malajalama</lingvo>
  <lingvo kodo="mn">mongola</lingvo>
  <lingvo kodo="mo">moldava</lingvo>
  <lingvo kodo="mr">marata</lingvo>
  <lingvo kodo="ms">malaja</lingvo>
  <lingvo kodo="mt">malta</lingvo>
  <lingvo kodo="my">birma</lingvo>
  <lingvo kodo="na">naura</lingvo>
  <lingvo kodo="nb">skribnorvega</lingvo>
  <lingvo kodo="nd">norda</lingvo>
  <lingvo kodo="ne">nepala</lingvo>
  <lingvo kodo="nl">nederlanda</lingvo>
  <lingvo kodo="nn">novnorvega</lingvo>
  <lingvo kodo="no">norvega</lingvo>
  <lingvo kodo="nv">navaha</lingvo>
  <lingvo kodo="ny">njanĝa</lingvo>
  <lingvo kodo="oc">okcitana</lingvo>
  <lingvo kodo="om">oroma</lingvo>
  <lingvo kodo="or">odia</lingvo>
  <lingvo kodo="os">oseta</lingvo>
  <lingvo kodo="ota">osmanida</lingvo>
  <lingvo kodo="pa">panĝaba</lingvo>
  <lingvo kodo="pl">pola</lingvo>
  <lingvo kodo="pnb">okcidentpanĝaba</lingvo>
  <lingvo kodo="ps">paŝtua</lingvo>
  <lingvo kodo="pt">portugala</lingvo>
  <lingvo kodo="qu">keĉua</lingvo>
  <lingvo kodo="rm">romanĉa</lingvo>
  <lingvo kodo="rn">burunda</lingvo>
  <lingvo kodo="ro">rumana</lingvo>
  <lingvo kodo="ru">rusa</lingvo>
  <lingvo kodo="rw">ruanda</lingvo>
  <lingvo kodo="sa">sanskrita</lingvo>
  <lingvo kodo="sc">sarda</lingvo>
  <lingvo kodo="scn">sicilia</lingvo>
  <lingvo kodo="sd">sinda</lingvo>
  <lingvo kodo="se">nordsamea</lingvo>
  <lingvo kodo="sg">sangoa</lingvo>
  <lingvo kodo="sgn">signuna</lingvo> <!-- esperanta (rudimenta) gestolingvo, Signuno kaj aldonoj -->
  <lingvo kodo="sh">serbokroata</lingvo>
  <lingvo kodo="si">sinhala</lingvo>
  <lingvo kodo="sk">slovaka</lingvo>
  <lingvo kodo="sl">slovena</lingvo>
  <lingvo kodo="sm">samoa</lingvo>
  <lingvo kodo="sn">ŝona</lingvo>
  <lingvo kodo="so">somala</lingvo>
  <lingvo kodo="sq">albana</lingvo>
  <lingvo kodo="sr">serba</lingvo>
  <lingvo kodo="ss">svazia</lingvo>
  <lingvo kodo="st">sota</lingvo>
  <lingvo kodo="su">sunda</lingvo>
  <lingvo kodo="sv">sveda</lingvo>
  <lingvo kodo="sw">svahila</lingvo>
  <lingvo kodo="syc">siria</lingvo>
  <lingvo kodo="ta">tamila</lingvo>
  <lingvo kodo="tcy">tulua</lingvo>
  <lingvo kodo="te">telugua</lingvo>
  <lingvo kodo="tg">taĝika</lingvo>
  <lingvo kodo="th">taja</lingvo>
  <lingvo kodo="ti">tigraja</lingvo>
  <lingvo kodo="tk">turkmena</lingvo>
  <lingvo kodo="tl">filipina</lingvo>
  <lingvo kodo="tn">cvana</lingvo>
  <lingvo kodo="to">tongaa</lingvo>
  <lingvo kodo="tok">tokipona</lingvo>
  <!-- <lingvo kodo="tp">tokipona</lingvo> anst. per tok -->
  <lingvo kodo="tr">turka</lingvo>
  <lingvo kodo="ts">conga</lingvo>
  <lingvo kodo="tt">tatara</lingvo>
  <lingvo kodo="tw">tvia</lingvo>
  <lingvo kodo="ug">ujgura</lingvo>
  <lingvo kodo="uk">ukraina</lingvo>
  <lingvo kodo="ur">urdua</lingvo>
  <lingvo kodo="uz">uzbeka</lingvo>
  <lingvo kodo="ve">vendaa</lingvo>
  <lingvo kodo="vi">vjetnama</lingvo>
  <lingvo kodo="vo">volapuka</lingvo>
  <lingvo kodo="vro">voroa</lingvo>
  <lingvo kodo="war">varaja</lingvo>
  <lingvo kodo="wo">volofa</lingvo>
  <lingvo kodo="wym">vilamovica</lingvo>
  <lingvo kodo="xal">kalmuka</lingvo>
  <lingvo kodo="xcl">klasikarmena</lingvo>
  <lingvo kodo="xh">kosa</lingvo>
  <lingvo kodo="yi">jida</lingvo>
  <lingvo kodo="yo">joruba</lingvo>
  <lingvo kodo="yue">kantona</lingvo>
  <lingvo kodo="za">ĝuanga</lingvo>
  <lingvo kodo="zbl">blisa</lingvo>
  <lingvo kodo="zh">ĉina</lingvo>
  <lingvo kodo="zu">zulua</lingvo>
</lingvoj>
