<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE ordigo [

<!ELEMENT ordigo (lingvo+)*>

<!ELEMENT lingvo (l*,r*,i*)>
<!ATTLIST lingvo
    lng ID #REQUIRED  
    kiel IDREF #IMPLIED
    kreu-regulojn (jes|ne) #IMPLIED
    klaso CDATA #IMPLIED
    silab CDATA #IMPLIED    
    ignorendaj CDATA #IMPLIED
    minusklo CDATA #IMPLIED
> 

<!ELEMENT l (#PCDATA|g)*>
<!ATTLIST l
    name NMTOKEN #REQUIRED
    n CDATA #IMPLIED
    minus CDATA #IMPLIED
> 

<!ELEMENT g (#PCDATA)>
<!ELEMENT r (#PCDATA)>
<!ELEMENT i (#PCDATA)>
]>

<!--
  Ordo de literoj en la indeksoj. La ordigo ene de litero-ĉapitro estas farata de Saxon, kiu siavice uzas
  Java (subklasojn de java.util.Comparator). 

  Per kreu-regulojn=jes oni povas krei regulojn uzeblajn per
  java.text.RuleBasedCollator (https://docs.oracle.com/javase/7/docs/api/java/text/RuleBasedCollator.html).
  Tamen pli novaj versioj de Saxon nun preferas, ke oni donu rekte Javo-klason por la ordigo. 
  Tiuj estas jene troveblaj: $VOKO/jav/de/steloj/respiro/ resp. $VOKO/xsl/respiro.jar 

  Alivorte kreu-reguloj / klaso tie ĉi donita ne plu estas influa, anstataue la
  ordigo-klaso estas rekte donita en xsl/inx_ordigo2.inc, t.e. mane redaktita tie

  Informojn kiel vi povas ĝustigi ordigon de lingvo per reguloj, vi trovas ekz. tie ĉi en la reto:
  http://userguide.icu-project.org/collation/customization


  <l>...</l> (grupo de) litero(j), sub kiu ordiĝas vortoj, kiuj tiel komenciĝas
  n=..., anstataŭ unuopaj literoj temas pri ĉeneto da literoj, ekz. "ch" anstataŭ "ĉ"
  <i> ignorendaj literoj dum ordigo - uzata ĉe kreado de ordigo-reguloj por Saxon, 
      sed nun ne plu uzata prefere al Javo-klaso
  <r> (replace) - anstataŭigo de litergrupoj samvalidaj kiel alia litero, 
      ekz. "ae" anstataŭ "ä" en la germana, same por Saxon, sed ne plu uzata nun


  Referencoj:
  - ordigo de aziaj skriboj: https://www.researchgate.net/publication/242638651_A_Study_on_Collation_of_Languages_from_Developing_Asia/download
-->

<ordigo>

<lingvo lng="eo" kreu-regulojn="jes" klaso="de.steloj.respiro.EsperantoCollator">
 <l name="a">a,A</l>
 <l name="b">b,B</l>
 <l name="c">c,C</l>
 <l name="cx">&#x0109;,&#x0108;</l>
 <l name="d">d,D</l>
 <l name="e">e,E</l>
 <l name="f">f,F</l>
 <l name="g">g,G</l>
 <l name="gx">&#x011d;,&#x011c;</l>
 <l name="h">h,H</l>
 <l name="hx">&#x0125;,&#x0124;</l>
 <l name="i">i,I</l>
 <l name="j">j,J</l>
 <l name="jx">&#x0135;,&#x0134;</l>
 <l name="k">k,K</l>
 <l name="l">l,L</l>
 <l name="m">m,M</l>
 <l name="n">n,N</l>
 <l name="o">o,O</l>
 <l name="p">p,P</l>
 <l name="r">r,R</l>
 <l name="s">s,S</l>
 <l name="sx">&#x015d;,&#x015c;</l>
 <l name="t">t,T</l>
 <l name="u">u,U</l>
 <l name="ux">&#x016d;,&#x016c;</l>
 <l name="v">v,V</l>
 <l name="z">z,Z</l>
</lingvo>

<!-- amhara -->
<lingvo lng="am"> 
 <l name="h">ሀሁሂሃሄህሆ</l>
 <l name="l">ለሉሊላሌልሎሏ</l>
 <l name="hh">ሐሑሒሓሔሕሖሗ</l>
 <l name="m">መሙሚማሜምሞሟ</l>
 <l name="sx">ሠሡሢሣሤሥሦሧ</l>
 <l name="r">ረሩሪራሬርሮሯ</l>
 <l name="s">ሰሱሲሳሴስሶሷ</l>
 <l name="sy">ሸሹሺሻሼሽሾሿ</l>
 <l name="q">ቀቁቂቃቄቅቆቈቊቋቌቍ</l>
 <l name="b">በቡቢባቤብቦቧ</l>
 <l name="v">ቨቩቪቫቬቭቮቯ</l>
 <l name="t">ተቱቲታቴትቶቷ</l>
 <l name="cy">ቸቹቺቻቼችቾቿ</l>
 <l name="hx">ኀኁኂኃኄኅኆኈኊኋኌኍ</l>
 <l name="n">ነኑኒናኔንኖኗ</l>
 <l name="ny">ኘኙኚኛኜኝኞኟ</l>
 <l name="al">አኡኢኣኤእኦኧ</l>
 <l name="k">ከኩኪካኬክኮኰኲኳኴኵ</l>
 <l name="x">ኸኹኺኻኼኽኾዀዂዃዄዅ</l>
 <l name="w">ወዉዊዋዌውዎ</l>
 <l name="ar">ዐዑዒዓዔዕዖ</l>
 <l name="z">ዘዙዚዛዜዝዞዟ</l>
 <l name="zy">ዠዡዢዣዤዥዦዧ</l>
 <l name="y">የዩዪያዬይዮ</l>
 <l name="d">ደዱዲዳዴድዶዷ</l>
 <l name="gy">ጀጁጂጃጄጅጆጇ</l>
 <l name="g">ገጉጊጋጌግጎጐጒጓጔጕ</l>
 <l name="tt">ጠጡጢጣጤጥጦጧ</l>
 <l name="cv">ጨጩጪጫጬጭጮጯ</l>
 <l name="pp">ጰጱጲጳጴጵጶጷ</l>
 <l name="ss">ጸጹጺጻጼጽጾጿ</l>
 <l name="sz">ፀፁፂፃፄፅፆ</l>
 <l name="f">ፈፉፊፋፌፍፎፏ</l>
 <l name="p">ፐፑፒፓፔፕፖፗ</l>
</lingvo>


<!-- araba -->
<lingvo lng="ar"> 
 <l name="a">&#x0627;&#x0623;&#x0625;&#x0622;&#x0671;&#x0621;</l>
 <l name="b">&#x0628;</l>
 <l name="c">&#x062a;&#x0629;</l>
 <l name="d">&#x062b;</l>
 <l name="e">&#x062c;</l>
 <l name="f">&#x062d;</l>
 <l name="g">&#x062e;</l>
 <l name="h">&#x062f;</l>
 <l name="i">&#x0630;</l>
 <l name="j">&#x0631;</l>
 <l name="k">&#x0632;</l>
 <l name="l">&#x0633;</l>
 <l name="m">&#x0634;</l>
 <l name="n">&#x0635;</l>
 <l name="o">&#x0636;</l>
 <l name="p">&#x0637;</l>
 <l name="q">&#x0638;</l>
 <l name="r">&#x0639;</l>
 <l name="s">&#x063a;</l>
 <l name="t">&#x0641;</l>
 <l name="u">&#x0642;</l>
 <l name="v">&#x0643;</l>
 <l name="w">&#x0644;</l>
 <l name="x">&#x0645;</l>
 <l name="y">&#x0646;</l>
 <l name="z">&#x0647;</l>
</lingvo>

<!-- armena 
https://en.wikibooks.org/wiki/Armenian/Alphabet -->
<lingvo lng="hy">
 <l name="a">աԱ</l>
 <l name="b">բԲ</l>
 <l name="g">գԳ</l>
 <l name="d">դԴ</l>
 <l name="e">եԵ</l>
 <l name="z">զԶ</l>
 <l name="eh">էԷ</l>
 <l name="u">ըԸ</l>
 <l name="th">թԹ</l>
 <l name="zh">ժԺ</l>
 <l name="i">իԻ</l>
 <l name="l">լԼ</l>
 <l name="x">խԽ</l>
 <l name="tz">ծԾ</l>
 <l name="k">կԿ</l>
 <l name="h">հՀ</l>
 <l name="dz">ձՁ</l>
 <l name="gl">ղՂ</l>
 <l name="cj">ճՃ</l>
 <l name="m">մՄ</l>
 <l name="y">յՅ</l>
 <l name="n">նՆ</l>
 <l name="sh">շՇ</l>
 <l name="o">ոՈ</l>
 <l name="ch">չՉ</l>
 <l name="p">պՊ</l>
 <l name="j">ջՋ</l>
 <l name="rr">ռՌ</l>
 <l name="s">սՍ</l>
 <l name="v">վՎ</l>
 <l name="t">տՏ</l>
 <l name="r">րՐ</l>
 <l name="c">ցՑ</l>
 <l name="w">ւՒ</l>
 <l name="ph">փՓ</l>
 <l name="q">քՔ</l>
 <l name="oh">օՕ</l>
 <l name="f">ֆՖ</l>
</lingvo>

<!-- belorusa -->
<lingvo lng="be">
 <l name="a">&#x0430;&#x0410;</l>
 <l name="b">&#x0431;&#x0411;</l>
 <l name="v">&#x0432;&#x0412;</l>
 <l name="g">&#x0433;&#x0413;</l>
 <l name="d">&#x0434;&#x0414;</l>
 <l name="je">&#x0435;&#x0415;</l>
 <l name="jo">&#x0451;&#x0401;</l>
 <l name="zh">&#x0436;&#x0416;</l>
 <l name="z">&#x0437;&#x0417;</l>
 <l name="i">&#x0456;&#x0406;</l>
 <l name="j">&#x0439;&#x0419;</l>
 <l name="k">&#x043a;&#x041a;</l>
 <l name="l">&#x043b;&#x041b;</l>
 <l name="m">&#x043c;&#x041c;</l>
 <l name="n">&#x043d;&#x041d;</l>
 <l name="o">&#x043e;&#x041e;</l>
 <l name="p">&#x043f;&#x041f;</l>
 <l name="r">&#x0440;&#x0420;</l>
 <l name="s">&#x0441;&#x0421;</l>
 <l name="t">&#x0442;&#x0422;</l>
 <l name="u">&#x0443;&#x0423;&#x045e;&#x040e;</l>
 <l name="f">&#x0444;&#x0424;</l>
 <l name="h">&#x0445;&#x0425;</l>
 <l name="c">&#x0446;&#x0426;</l>
 <l name="ch">&#x0447;&#x0427;</l>
 <l name="sh">&#x0448;&#x0428;</l>
 <l name="y">&#x044b;&#x042b;</l>
 <l name="mo">&#x044c;&#x042c;</l>
 <l name="e">&#x044d;&#x042d;</l>
 <l name="ju">&#x044e;&#x042e;</l>
 <l name="ja">&#x044f;&#x042f;</l>
</lingvo>

<!-- bengala 
https://www.ijcaonline.org/research/volume126/number11/shabnam-2015-ijca-906224.pdf -->
<lingvo lng="bn">
 <!-- vokaloj: ĉu ili havu apartajn grupojn
      aŭ subordiĝu sub konsonantojn? -->
 <l name="oa">&#x0985;</l> <!-- অ -->
 <l name="a">&#x0986;</l> <!-- আ -->
 <l name="i">&#x0987;</l> <!-- ই -->
 <l name="ii">&#x0988;</l> <!-- ঈ -->
 <l name="u">&#x0989;</l> <!-- উ -->
 <l name="uu">&#x098A;</l> <!-- ঊ -->
 <l name="ri">&#x098B;</l> <!-- ঋ -->
 <l name="e">&#x098F;</l> <!-- এ -->
 <l name="oi">&#x0990;</l> <!-- ঐ -->
 <l name="o">&#x0993;</l> <!-- ও -->
 <l name="ou">&#x0994;</l> <!-- ঔ -->

 <!-- konsonantoj -->
 <l name="k">&#x0995;</l> <!-- ক -->
 <l name="kh">&#x0996;</l> <!-- খ -->
 <l name="g">&#x0997;</l> <!-- গ -->
 <l name="gh">&#x0998;</l> <!-- ঘ -->
 <l name="ng">&#x0999;</l> <!-- ঙ -->
 <l name="ch">&#x099A;</l> <!-- চ -->
 <l name="cx">&#x099B;</l> <!-- ছ -->
 <l name="jy">&#x099C;</l> <!-- জ -->
 <l name="jh">&#x099D;</l> <!-- ঝ -->
 <l name="nj">&#x099E;</l> <!-- ঞ -->
 <l name="T">&#x099F;</l> <!-- ট -->
 <l name="Th">&#x09A0;</l> <!-- ঠ -->
 <l name="D">&#x09A1;</l> <!-- ড -->
 <l name="Dh">&#x09A2;</l> <!-- ঢ -->
 <l name="N">&#x09A3;</l> <!-- র্ -->
 <l name="t">&#x09A4;</l> <!-- ত -->
 <l name="th">&#x09A5;</l> <!-- থ -->
 <l name="d">&#x09A6;</l> <!-- দ -->
 <l name="dh">&#x09A7;</l> <!-- ধ -->
 <l name="n">&#x09A8;</l> <!-- ন -->
 <l name="p">&#x09AA;</l> <!-- প -->
 <l name="ph">&#x09AB;</l> <!-- ফ -->
 <l name="b">&#x09AC;</l> <!-- ব -->
 <l name="bh">&#x09AD;</l> <!-- ভ -->
 <l name="m">&#x09AE;</l> <!-- ম -->
 <l name="j">&#x09AF;</l> <!-- য -->
 <l name="r">&#x09B0;</l> <!-- র -->
 <l name="l">&#x09B2;</l> <!-- ল -->
 <l name="sh">&#x09B6;</l> <!-- শ -->
 <l name="S">&#x09B7;</l> <!-- ষ -->
 <l name="s">&#x09B8;</l> <!-- স -->
 <l name="h">&#x09B9;</l> <!-- হ -->
 <l name="R">&#x09DC;</l> <!-- ড় -->
 <l name="Rh">&#x09DD;</l> <!-- ঢ় -->
 <l name="y">&#x09DF;</l> <!-- য় -->
 <!-- <l name="tx">&#x09CE;</l>  ৎ -->
 <!-- <l name="Nx">&#x0982;</l>  ংাং -->
 <!-- <l name="hx">&#x0983;</l>  xং  -->
 <!-- <l name="nx">&#x0981;</l>  xং -->
</lingvo>

<!-- bulgara -->
<lingvo lng="bg">
 <l name="a">&#x0430;&#x0410;</l>
 <l name="b">&#x0431;&#x0411;</l>
 <l name="v">&#x0432;&#x0412;</l>
 <l name="g">&#x0433;&#x0413;</l>
 <l name="d">&#x0434;&#x0414;</l>
 <l name="je">&#x0435;&#x0415;</l>
 <l name="zh">&#x0436;&#x0416;</l>
 <l name="z">&#x0437;&#x0417;</l>
 <l name="i">&#x0438;&#x0418;</l>
 <l name="j">&#x0439;&#x0419;</l>
 <l name="k">&#x043a;&#x041a;</l>
 <l name="l">&#x043b;&#x041b;</l>
 <l name="m">&#x043c;&#x041c;</l>
 <l name="n">&#x043d;&#x041d;</l>
 <l name="o">&#x043e;&#x041e;</l>
 <l name="p">&#x043f;&#x041f;</l>
 <l name="r">&#x0440;&#x0420;</l>
 <l name="s">&#x0441;&#x0421;</l>
 <l name="t">&#x0442;&#x0422;</l>
 <l name="u">&#x0443;&#x0423;</l>
 <l name="f">&#x0444;&#x0424;</l>
 <l name="h">&#x0445;&#x0425;</l>
 <l name="c">&#x0446;&#x0426;</l>
 <l name="ch">&#x0447;&#x0427;</l>
 <l name="sh">&#x0448;&#x0428;</l>
 <l name="shch">&#x0449;&#x0429;</l>
 <l name="mm">&#x044a;&#x042a;</l>
 <l name="y">&#x044b;&#x042b;</l>
 <l name="mo">&#x044c;&#x042c;</l>
 <l name="e">&#x044d;&#x042d;</l>
 <l name="ju">&#x044e;&#x042e;</l>
 <l name="ja">&#x044f;&#x042f;</l>
</lingvo>


<!-- tibeta 

Oni ordigas la tibetan laŭ-silabe kaj ne laŭ-litere,
vd. la tabelon https://web.archive.org/web/20160428223852/https://developer.mimer.com/charts/tibetan.htm
Unikodo tibeta: https://de.wikipedia.org/wiki/Unicodeblock_Tibetisch

Per atributo @silab ni donas silabigan signon, sed la algoritmo fakte 
ne bezonas ĝin. Per voko:max-prefix en inx_ordigo2.xsl ni simple serĉas la plej
longan litergrupon egalan al la vortkomenco.

Vortaroj: 
http://www.eng-tib.com/
https://dictionary.christian-steinert.de/
http://www.thlib.org/reference/dictionaries/tibetan-dictionary/translate.php

-->
<lingvo lng="bo" silab="&#x0F0B;">
<l name="ka">
    <g>&#x0F40;</g>
    <g>&#x0F88;&#x0F90;</g>
    <g>&#x0F51;&#x0F40;</g>
    <g>&#x0F56;&#x0F40;</g>
    <g>&#x0F62;&#x0F90;</g>
    <g>&#x0F63;&#x0F90;</g>
    <g>&#x0F66;&#x0F90;</g>
    <g>&#x0F56;&#x0F62;&#x0F90;</g>
    <g>&#x0F56;&#x0F66;&#x0F90;</g>
</l>
<l name="kha">
    <g>&#x0F41;</g>
    <g>&#x0F88;&#x0F91;</g>
    <g>&#x0F58;&#x0F41;</g>
    <g>&#x0F60;&#x0F41;</g>
</l>
<l name="ga">
    <g>&#x0F42;</g>
    <g>&#x0F51;&#x0F42;&#x0F42;</g>
    <g>&#x0F51;&#x0F42;&#x0F44;</g>
    <g>&#x0F51;&#x0F42;&#x0F51;</g>
    <g>&#x0F51;&#x0F42;&#x0F53;</g>
    <g>&#x0F51;&#x0F42;&#x0F56;</g>
    <g>&#x0F51;&#x0F42;&#x0F5D;</g>
    <g>&#x0F51;&#x0F42;&#x0F60;</g>
    <g>&#x0F51;&#x0F42;&#x0F62;</g>
    <g>&#x0F51;&#x0F42;&#x0F63;</g>
    <g>&#x0F51;&#x0F42;&#x0F66;</g>
    <g>&#x0F51;&#x0F42;&#x0F74;</g>
    <g>&#x0F51;&#x0F42;&#x0F7A;</g>
    <g>&#x0F51;&#x0F42;&#x0F7C;</g>
    <g>&#x0F51;&#x0F42;&#x0FB1;</g>
    <g>&#x0F51;&#x0F42;&#x0FB2;</g>
    <g>&#x0F56;&#x0F42;&#x0F42;</g>
    <g>&#x0F56;&#x0F42;&#x0F51;</g>
    <g>&#x0F56;&#x0F42;&#x0F58;</g>
    <g>&#x0F56;&#x0F42;&#x0F7E;</g>
    <g>&#x0F56;&#x0F42;&#x0F5D;</g>
    <g>&#x0F56;&#x0F42;&#x0F62;</g>
    <g>&#x0F56;&#x0F42;&#x0F7A;</g>
    <g>&#x0F56;&#x0F42;&#x0F7C;</g>
    <g>&#x0F56;&#x0F42;&#x0FB1;</g>
    <g>&#x0F56;&#x0F42;&#x0FB2;</g>
    <g>&#x0F58;&#x0F42;&#x0F62;</g>
    <g>&#x0F58;&#x0F42;&#x0F63;</g>
    <g>&#x0F58;&#x0F42;&#x0F74;</g>
    <g>&#x0F58;&#x0F42;&#x0F7C;</g>
    <g>&#x0F58;&#x0F42;&#x0FB1;</g>
    <g>&#x0F58;&#x0F42;&#x0FB2;</g>
    <g>&#x0F60;&#x0F42;&#x0F42;</g>
    <g>&#x0F60;&#x0F42;&#x0F44;</g>
    <g>&#x0F60;&#x0F42;&#x0F51;</g>
    <g>&#x0F60;&#x0F42;&#x0F53;</g>
    <g>&#x0F60;&#x0F42;&#x0F56;</g>
    <g>&#x0F60;&#x0F42;&#x0F58;</g>
    <g>&#x0F60;&#x0F42;&#x0F7E;</g>
    <g>&#x0F60;&#x0F42;&#x0F60;</g>
    <g>&#x0F60;&#x0F42;&#x0F62;</g>
    <g>&#x0F60;&#x0F42;&#x0F63;</g>
    <g>&#x0F60;&#x0F42;&#x0F66;</g>
    <g>&#x0F60;&#x0F42;&#x0F72;</g>
    <g>&#x0F60;&#x0F42;&#x0F74;</g>
    <g>&#x0F60;&#x0F42;&#x0F7A;</g>
    <g>&#x0F60;&#x0F42;&#x0F7C;</g>
    <g>&#x0F60;&#x0F42;&#x0FB1;</g>
    <g>&#x0F60;&#x0F42;&#x0FB2;</g>
    <g>&#x0F62;&#x0F92;</g>
    <g>&#x0F63;&#x0F92;</g>
    <g>&#x0F66;&#x0F92;</g>
    <g>&#x0F56;&#x0F62;&#x0F92;</g>
    <g>&#x0F56;&#x0F66;&#x0F92;</g>
</l>
<l name="nga">
    <g>&#x0F44;</g>
    <g>&#x0F51;&#x0F44;&#x0F42;</g>
    <g>&#x0F51;&#x0F44;&#x0F44;</g>
    <g>&#x0F51;&#x0F44;&#x0F53;</g>
    <g>&#x0F51;&#x0F44;&#x0F62;</g>
    <g>&#x0F51;&#x0F44;&#x0F74;</g>
    <g>&#x0F51;&#x0F44;&#x0F7C;</g>
    <g>&#x0F58;&#x0F44;&#x0F42;</g>
    <g>&#x0F58;&#x0F44;&#x0F53;</g>
    <g>&#x0F58;&#x0F44;&#x0F60;</g>
    <g>&#x0F58;&#x0F44;&#x0F62;</g>
    <g>&#x0F58;&#x0F44;&#x0F63;</g>
    <g>&#x0F58;&#x0F44;&#x0F7C;</g>
    <g>&#x0F62;&#x0F94;</g>
    <g>&#x0F63;&#x0F94;</g>
    <g>&#x0F66;&#x0F94;</g>
    <g>&#x0F56;&#x0F62;&#x0F94;</g>
    <g>&#x0F56;&#x0F66;&#x0F94;</g>
</l>
<l name="ca">
    <g>&#x0F45;</g>
    <g>&#x0F42;&#x0F45;</g>
    <g>&#x0F56;&#x0F45;</g>
    <g>&#x0F63;&#x0F95;</g>
    <g>&#x0F56;&#x0F63;&#x0F95;</g>
</l>
<l name="cha">
    <g>&#x0F46;</g>
    <g>&#x0F58;&#x0F46;</g>
    <g>&#x0F60;&#x0F46;</g>
</l>
<l name="ja">
    <g>&#x0F47;</g>
    <g>&#x0F58;&#x0F47;</g>
    <g>&#x0F60;&#x0F47;</g>
    <g>&#x0F62;&#x0F97;</g>
    <g>&#x0F63;&#x0F97;</g>
    <g>&#x0F56;&#x0F62;&#x0F97;</g>
</l>
<l name="nya">
    <g>&#x0F49;</g>
    <g>&#x0F8B;&#x0F99;</g>
    <g>&#x0F42;&#x0F49;</g>
    <g>&#x0F58;&#x0F49;</g>
    <g>&#x0F62;&#x0F99;</g>
    <g>&#x0F66;&#x0F99;</g>
    <g>&#x0F56;&#x0F62;&#x0F99;</g>
    <g>&#x0F56;&#x0F66;&#x0F99;</g>
</l>
<l name="ta">
    <g>&#x0F4F;</g>
    <g>&#x0F4A;</g>
    <g>&#x0F42;&#x0F4F;</g>
    <g>&#x0F56;&#x0F4F;</g>
    <g>&#x0F62;&#x0F9F;</g>
    <g>&#x0F63;&#x0F9F;</g>
    <g>&#x0F66;&#x0F9F;</g>
    <g>&#x0F56;&#x0F62;&#x0F9F;</g>
    <g>&#x0F56;&#x0F63;&#x0F9F;</g>
    <g>&#x0F56;&#x0F66;&#x0F9F;</g>
</l>
<l name="tha">
    <g>&#x0F50;</g>
    <g>&#x0F4B;</g>
    <g>&#x0F58;&#x0F50;</g>
    <g>&#x0F60;&#x0F50;</g>
</l>
<l name="da">
    <g>&#x0F51;</g>
    <g>&#x0F4C;</g>
    <g>&#x0F42;&#x0F51;&#x0F42;</g>
    <g>&#x0F42;&#x0F51;&#x0F44;</g>
    <g>&#x0F42;&#x0F51;&#x0F53;</g>
    <g>&#x0F42;&#x0F51;&#x0F56;</g>
    <g>&#x0F42;&#x0F51;&#x0F58;</g>
    <g>&#x0F42;&#x0F51;&#x0F7E;</g>
    <g>&#x0F42;&#x0F51;&#x0F60;</g>
    <g>&#x0F42;&#x0F51;&#x0F62;</g>
    <g>&#x0F42;&#x0F51;&#x0F63;</g>
    <g>&#x0F42;&#x0F51;&#x0F66;</g>
    <g>&#x0F42;&#x0F51;&#x0F72;</g>
    <g>&#x0F42;&#x0F51;&#x0F74;</g>
    <g>&#x0F42;&#x0F51;&#x0F7A;</g>
    <g>&#x0F42;&#x0F51;&#x0F7C;</g>
    <g>&#x0F56;&#x0F51;&#x0F42;</g>
    <g>&#x0F56;&#x0F51;&#x0F58;</g>
    <g>&#x0F56;&#x0F51;&#x0F7E;</g>
    <g>&#x0F56;&#x0F51;&#x0F60;</g>
    <g>&#x0F56;&#x0F51;&#x0F62;</g>
    <g>&#x0F56;&#x0F51;&#x0F63;</g>
    <g>&#x0F56;&#x0F51;&#x0F66;</g>
    <g>&#x0F56;&#x0F51;&#x0F74;</g>
    <g>&#x0F56;&#x0F51;&#x0F7A;</g>
    <g>&#x0F56;&#x0F51;&#x0F7C;</g>
    <g>&#x0F58;&#x0F51;&#x0F42;</g>
    <g>&#x0F58;&#x0F51;&#x0F44;</g>
    <g>&#x0F58;&#x0F51;&#x0F53;</g>
    <g>&#x0F58;&#x0F51;&#x0F60;</g>
    <g>&#x0F58;&#x0F51;&#x0F62;</g>
    <g>&#x0F58;&#x0F51;&#x0F74;</g>
    <g>&#x0F58;&#x0F51;&#x0F7A;</g>
    <g>&#x0F58;&#x0F51;&#x0F7C;</g>
    <g>&#x0F60;&#x0F51;&#x0F42;</g>
    <g>&#x0F60;&#x0F51;&#x0F44;</g>
    <g>&#x0F60;&#x0F51;&#x0F51;</g>
    <g>&#x0F60;&#x0F51;&#x0F53;</g>
    <g>&#x0F60;&#x0F51;&#x0F56;</g>
    <g>&#x0F60;&#x0F51;&#x0F58;</g>
    <g>&#x0F60;&#x0F51;&#x0F7E;</g>
    <g>&#x0F60;&#x0F51;&#x0F5D;</g>
    <g>&#x0F60;&#x0F51;&#x0F60;</g>
    <g>&#x0F60;&#x0F51;&#x0F62;</g>
    <g>&#x0F60;&#x0F51;&#x0F63;</g>
    <g>&#x0F60;&#x0F51;&#x0F66;</g>
    <g>&#x0F60;&#x0F51;&#x0F72;</g>
    <g>&#x0F60;&#x0F51;&#x0F74;</g>
    <g>&#x0F60;&#x0F51;&#x0F7A;</g>
    <g>&#x0F60;&#x0F51;&#x0F7C;</g>
    <g>&#x0F60;&#x0F51;&#x0FB2;</g>
    <g>&#x0F62;&#x0FA1;</g>
    <g>&#x0F63;&#x0FA1;</g>
    <g>&#x0F66;&#x0FA1;</g>
    <g>&#x0F56;&#x0F62;&#x0FA1;</g>
    <g>&#x0F56;&#x0F63;&#x0FA1;</g>
    <g>&#x0F56;&#x0F66;&#x0FA1;</g>
</l>
<l name="na">
    <g>&#x0F53;</g>
    <g>&#x0F4E;</g>
    <g>&#x0F42;&#x0F53;&#x0F42;</g>
    <g>&#x0F42;&#x0F53;&#x0F44;</g>
    <g>&#x0F42;&#x0F53;&#x0F51;</g>
    <g>&#x0F42;&#x0F53;&#x0F53;</g>
    <g>&#x0F42;&#x0F53;&#x0F58;</g>
    <g>&#x0F42;&#x0F53;&#x0F7E;</g>
    <g>&#x0F42;&#x0F53;&#x0F5D;</g>
    <g>&#x0F42;&#x0F53;&#x0F60;</g>
    <g>&#x0F42;&#x0F53;&#x0F66;</g>
    <g>&#x0F42;&#x0F53;&#x0F74;</g>
    <g>&#x0F42;&#x0F53;&#x0F7C;</g>
    <g>&#x0F58;&#x0F53;&#x0F42;</g>
    <g>&#x0F58;&#x0F53;&#x0F44;</g>
    <g>&#x0F58;&#x0F53;&#x0F53;</g>
    <g>&#x0F58;&#x0F53;&#x0F56;</g>
    <g>&#x0F58;&#x0F53;&#x0F58;</g>
    <g>&#x0F58;&#x0F53;&#x0F7E;</g>
    <g>&#x0F58;&#x0F53;&#x0F60;</g>
    <g>&#x0F58;&#x0F53;&#x0F62;</g>
    <g>&#x0F58;&#x0F53;&#x0F63;</g>
    <g>&#x0F58;&#x0F53;&#x0F74;</g>
    <g>&#x0F58;&#x0F53;&#x0F7A;</g>
    <g>&#x0F58;&#x0F53;&#x0F7C;</g>
    <g>&#x0F62;&#x0FA3;</g>
    <g>&#x0F66;&#x0FA3;</g>
    <g>&#x0F56;&#x0F62;&#x0FA3;</g>
    <g>&#x0F56;&#x0F66;&#x0FA3;</g>
</l>
<l name="pa">
    <g>&#x0F54;</g>
    <g>&#x0F89;&#x0FA4;</g>
    <g>&#x0F51;&#x0F54;&#x0F42;</g>
    <g>&#x0F51;&#x0F54;&#x0F44;</g>
    <g>&#x0F51;&#x0F54;&#x0F51;</g>
    <g>&#x0F51;&#x0F54;&#x0F60;</g>
    <g>&#x0F51;&#x0F54;&#x0F62;</g>
    <g>&#x0F51;&#x0F54;&#x0F63;</g>
    <g>&#x0F51;&#x0F54;&#x0F66;</g>
    <g>&#x0F51;&#x0F54;&#x0F74;</g>
    <g>&#x0F51;&#x0F54;&#x0F7A;</g>
    <g>&#x0F51;&#x0F54;&#x0F7C;&#x0F42;</g>
    <g>&#x0F51;&#x0F54;&#x0F7C;&#x0F44;</g>
    <g>&#x0F51;&#x0F54;&#x0F7C;&#x0F51;</g>
    <g>&#x0F51;&#x0F54;&#x0F7C;&#x0F53;</g>
    <g>&#x0F51;&#x0F54;&#x0F7C;&#x0F62;</g>
    <g>&#x0F51;&#x0F54;&#x0FB1;</g>
    <g>&#x0F51;&#x0F54;&#x0FB2;</g>
    <g>&#x0F63;&#x0FA4;</g>
    <g>&#x0F66;&#x0FA4;</g>
</l>
<l name="pha">
    <g>&#x0F55;</g>
    <g>&#x0F89;&#x0FA5;</g>
    <g>&#x0F60;&#x0F55;</g>
</l>
<l name="ba">
    <g>&#x0F56;</g>
    <g>&#x0F51;&#x0F56;&#x0F42;</g>
    <g>&#x0F51;&#x0F56;&#x0F44;</g>
    <g>&#x0F51;&#x0F56;&#x0F51;</g>
    <g>&#x0F51;&#x0F56;&#x0F53;</g>
    <g>&#x0F51;&#x0F56;&#x0F56;</g>
    <g>&#x0F51;&#x0F56;&#x0F60;</g>
    <g>&#x0F51;&#x0F56;&#x0F62;</g>
    <g>&#x0F51;&#x0F56;&#x0F63;</g>
    <g>&#x0F51;&#x0F56;&#x0F66;</g>
    <g>&#x0F51;&#x0F56;&#x0F74;</g>
    <g>&#x0F51;&#x0F56;&#x0F7A;</g>
    <g>&#x0F51;&#x0F56;&#x0F7C;</g>
    <g>&#x0F51;&#x0F56;&#x0FB1;</g>
    <g>&#x0F51;&#x0F56;&#x0FB2;</g>
    <g>&#x0F60;&#x0F56;&#x0F42;</g>
    <g>&#x0F60;&#x0F56;&#x0F44;</g>
    <g>&#x0F60;&#x0F56;&#x0F51;</g>
    <g>&#x0F60;&#x0F56;&#x0F53;</g>
    <g>&#x0F60;&#x0F56;&#x0F56;</g>
    <g>&#x0F60;&#x0F56;&#x0F58;</g>
    <g>&#x0F60;&#x0F56;&#x0F7E;</g>
    <g>&#x0F60;&#x0F56;&#x0F60;</g>
    <g>&#x0F60;&#x0F56;&#x0F62;</g>
    <g>&#x0F60;&#x0F56;&#x0F63;</g>
    <g>&#x0F60;&#x0F56;&#x0F66;</g>
    <g>&#x0F60;&#x0F56;&#x0F72;</g>
    <g>&#x0F60;&#x0F56;&#x0F74;</g>
    <g>&#x0F60;&#x0F56;&#x0F7A;</g>
    <g>&#x0F60;&#x0F56;&#x0F7C;</g>
    <g>&#x0F60;&#x0F56;&#x0FB1;</g>
    <g>&#x0F60;&#x0F56;&#x0FB2;</g>
    <g>&#x0F62;&#x0FA6;</g>
    <g>&#x0F63;&#x0FA6;</g>
    <g>&#x0F66;&#x0FA6;</g>
</l>
<l name="ma">
    <g>&#x0F58;</g>
    <g>&#x0F7E;</g>
    <g>&#x0F82;</g>
    <g>&#x0F83;</g>
    <g>&#x0F51;&#x0F58;&#x0F42;</g>
    <g>&#x0F51;&#x0F58;&#x0F44;</g>
    <g>&#x0F51;&#x0F58;&#x0F53;</g>
    <g>&#x0F51;&#x0F58;&#x0F5D;</g>
    <g>&#x0F51;&#x0F58;&#x0F60;</g>
    <g>&#x0F51;&#x0F58;&#x0F62;</g>
    <g>&#x0F51;&#x0F58;&#x0F66;</g>
    <g>&#x0F51;&#x0F58;&#x0F72;</g>
    <g>&#x0F51;&#x0F58;&#x0F74;</g>
    <g>&#x0F51;&#x0F58;&#x0F7A;</g>
    <g>&#x0F51;&#x0F58;&#x0F7C;&#x0F51;</g>
    <g>&#x0F51;&#x0F58;&#x0FB1;</g>
    <g>&#x0F62;&#x0FA8;</g>
    <g>&#x0F66;&#x0FA8;</g>
</l>
<l name="tsa">
    <g>&#x0F59;</g>
    <g>&#x0F42;&#x0F59;</g>
    <g>&#x0F56;&#x0F59;</g>
    <g>&#x0F62;&#x0FA9;</g>
    <g>&#x0F66;&#x0FA9;</g>
    <g>&#x0F56;&#x0F62;&#x0FA9;</g>
    <g>&#x0F56;&#x0F66;&#x0FA9;</g>
</l>
<l name="tsha">
    <g>&#x0F5A;</g>
    <g>&#x0F58;&#x0F5A;</g>
    <g>&#x0F60;&#x0F5A;</g>
</l>
<l name="dza">
    <g>&#x0F5B;</g>
    <g>&#x0F58;&#x0F5B;</g>
    <g>&#x0F60;&#x0F5B;</g>
    <g>&#x0F62;&#x0FAB;</g>
    <g>&#x0F56;&#x0F62;&#x0FAB;</g>
</l>
<l name="wa">
    <g>&#x0F5D;</g>
</l>
<l name="zha">
    <g>&#x0F5E;</g>
    <g>&#x0F42;&#x0F5E;</g>
    <g>&#x0F56;&#x0F5E;</g>
</l>
<l name="za">
    <g>&#x0F5F;</g>
    <g>&#x0F42;&#x0F5F;</g>
    <g>&#x0F56;&#x0F5F;</g>
</l>
<l name="-a">
    <g>&#x0F60;</g>
</l>
<l name="ya">
    <g>&#x0F61;</g>
    <g>&#x0F42;&#x0F61;</g>
</l>
<l name="ra">
    <g>&#x0F62;</g>
    <g>&#x0F6A;</g>
    <g>&#x0F56;&#x0F62;&#x0FB3;</g>
</l>
<l name="la">
    <g>&#x0F63;</g>
</l>
<l name="sha">
    <g>&#x0F64;</g>
    <g>&#x0F65;</g>
    <g>&#x0F42;&#x0F64;</g>
    <g>&#x0F56;&#x0F64;</g>
</l>
<l name="sa">
    <g>&#x0F66;</g>
    <g>&#x0F42;&#x0F66;&#x0F42;</g>
    <g>&#x0F42;&#x0F66;&#x0F44;</g>
    <g>&#x0F42;&#x0F66;&#x0F51;</g>
    <g>&#x0F42;&#x0F66;&#x0F53;</g>
    <g>&#x0F42;&#x0F66;&#x0F56;</g>
    <g>&#x0F42;&#x0F66;&#x0F60;</g>
    <g>&#x0F42;&#x0F66;&#x0F62;</g>
    <g>&#x0F42;&#x0F66;&#x0F63;</g>
    <g>&#x0F42;&#x0F66;&#x0F66;</g>
    <g>&#x0F42;&#x0F66;&#x0F72;</g>
    <g>&#x0F42;&#x0F66;&#x0F74;</g>
    <g>&#x0F42;&#x0F66;&#x0F7A;</g>
    <g>&#x0F42;&#x0F66;&#x0F7C;</g>
    <g>&#x0F56;&#x0F66;&#x0F42;</g>
    <g>&#x0F56;&#x0F66;&#x0F44;</g>
    <g>&#x0F56;&#x0F66;&#x0F51;</g>
    <g>&#x0F56;&#x0F66;&#x0F56;</g>
    <g>&#x0F56;&#x0F66;&#x0F58;</g>
    <g>&#x0F56;&#x0F66;&#x0F7E;</g>
    <g>&#x0F56;&#x0F66;&#x0F62;</g>
    <g>&#x0F56;&#x0F66;&#x0F63;</g>
    <g>&#x0F56;&#x0F66;&#x0F72;</g>
    <g>&#x0F56;&#x0F66;&#x0F74;</g>
    <g>&#x0F56;&#x0F66;&#x0F7A;</g>
    <g>&#x0F56;&#x0F66;&#x0F7C;</g>
    <g>&#x0F56;&#x0F66;&#x0FAD;</g>
    <g>&#x0F56;&#x0F66;&#x0FB2;</g>
    <g>&#x0F56;&#x0F66;&#x0FB3;</g>
</l>
<l name="ha">
    <g>&#x0F67;</g>
    <g>&#x0F63;&#x0FB7;</g>
</l>
<l name="a">
    <g>&#x0F68;</g>
</l>
</lingvo>

<!--  bretona -->
<lingvo lng="br" kreu-regulojn="jes" klaso="de.steloj.respiro.BretonCollator">
 <l name="a">a,A</l>
 <l name="b">b,B</l>
 <l name="ch" n="2">ch,cH,Ch,CH</l>
 <l name="cx" n="3">c'h,c'H,C'h,C'H</l>
 <l name="d">d,D</l>
 <l name="e">e,E</l> <!-- j,J ??? -->
 <l name="f">f,F</l>
 <l name="g">g,G</l>
 <l name="h">h,H</l>
 <l name="i">i,I</l>
 <l name="j">j,J</l>
 <l name="k">k,K</l>
 <l name="l">l,L</l>
 <l name="m">m,M</l>
 <l name="n">n,N,q,Q</l>
 <l name="o">o,O</l>
 <l name="p">p,P</l>
 <l name="r">r,R</l>
 <l name="s">s,S</l>
 <l name="t">t,T</l>
 <l name="u">u,U,ù,Ù,ü,Ü</l>
 <l name="v">v,V</l>
 <l name="w">w,W</l>
 <l name="x">x,X</l>
 <l name="y">y,Y</l>
 <l name="z">z,Z</l>
</lingvo>

<!-- kataluna -->
<lingvo lng="ca" kreu-regulojn="jes" klaso="de.steloj.respiro.CatalanCollator">
 <l name="a">a,A,à,À</l>
 <l name="b">b,B</l>
 <l name="c">c,C,ç,Ç</l>
 <l name="d">d,D</l>
 <l name="e">e,E,é,É,è,È</l>
 <l name="f">f,F</l>
 <l name="g">g,G</l>
 <l name="h">h,H</l>
 <l name="i">i,I,í,Í,ï,Ï</l>
 <l name="j">j,J</l>
 <l name="k">k,K</l>
 <l name="l">l,L,l·,L·</l>
 <l name="m">m,M</l>
 <l name="n">n,N</l>
 <l name="o">o,O,ó,Ó,ò,Ò</l>
 <l name="p">p,P</l>
 <l name="q">q,Q</l>
 <l name="r">r,R</l>
 <l name="s">s,S</l>
 <l name="t">t,T</l>
 <l name="u">u,U,ú,Ú,ü,Ü</l>
 <l name="v">v,V</l>
 <l name="w">w,W</l>
 <l name="x">x,X</l>
 <l name="y">y,Y</l>
 <l name="z">z,Z</l>
</lingvo>

<!-- ĉeĥa -->
<lingvo lng="cs">
 <l name="a">aAáÁ</l>
 <l name="b">bB</l>
 <l name="c">cC</l>
 <l name="cx">&#x010d;&#x010c;</l>
 <l name="d">dD&#x010f;&#x010e;</l>
 <l name="e">eEéÉ&#x011b;&#x011a;</l>
 <l name="f">fF</l>
 <l name="g">gG</l>
 <l name="h">hH</l>
 <l name="ch" n="2">chCh</l>
 <l name="i">iIíÍ</l>
 <l name="j">jJ</l>
 <l name="k">kK</l>
 <l name="l">lL</l>
 <l name="m">mM</l>
 <l name="n">nN&#x0148;&#x0147;</l>
 <l name="o">oO</l>
 <l name="p">pP</l>
 <l name="q">qQ</l>
 <l name="r">rR</l>
 <l name="rx">&#x0159;&#x0158;</l>
 <l name="s">sS</l>
 <l name="sx">&#x0161;&#x0160;</l>
 <l name="t">tT&#x0165;&#x0164;</l>
 <l name="u">uUúÚ&#x016f;&#x016e;</l>
 <l name="v">vV</l>
 <l name="w">wW</l>
 <l name="x">xX</l>
 <l name="y">yYýÝ</l>
 <l name="z">zZ</l>
 <l name="zx">&#x017e;&#x017d;</l>
</lingvo>


<!-- ĉuvaŝa -->
<lingvo lng="cv">
 <l name="a">&#x0430;&#x0410;</l>
 <l name="ax">&#x04D1;&#x04D0;</l>
 <l name="b">&#x0431;&#x0411;</l>
 <l name="v">&#x0432;&#x0412;</l>
 <l name="g">&#x0433;&#x0413;</l>
 <l name="d">&#x0434;&#x0414;</l>
 <l name="je">&#x0435;&#x0415;</l>
 <l name="jo">&#x0451;&#x0401;</l>
 <l name="jx">&#x04D7;&#x04D6;</l>
 <l name="zh">&#x0436;&#x0416;</l>
 <l name="z">&#x0437;&#x0417;</l>
 <l name="i">&#x0438;&#x0418;</l>
 <l name="j">&#x0439;&#x0419;</l>
 <l name="k">&#x043a;&#x041a;</l>
 <l name="l">&#x043b;&#x041b;</l>
 <l name="m">&#x043c;&#x041c;</l>
 <l name="n">&#x043d;&#x041d;</l>
 <l name="o">&#x043e;&#x041e;</l>
 <l name="p">&#x043f;&#x041f;</l>
 <l name="r">&#x0440;&#x0420;</l>
 <l name="s">&#x0441;&#x0421;</l>
 <l name="sx">&#x4AB;&#x4AA;&#xE7;&#xC7;</l>
 <l name="t">&#x0442;&#x0422;</l>
 <l name="u">&#x0443;&#x0423;</l>
 <l name="ux">&#x4F3;&#x4F2;</l>
 <l name="f">&#x0444;&#x0424;</l>
 <l name="h">&#x0445;&#x0425;</l>
 <l name="c">&#x0446;&#x0426;</l>
 <l name="ch">&#x0447;&#x0427;</l>
 <l name="sh">&#x0448;&#x0428;</l>
 <l name="shch">&#x0449;&#x0429;</l>
 <l name="mm">&#x044a;&#x042a;</l>
 <l name="y">&#x044b;&#x042b;</l>
 <l name="mo">&#x044c;&#x042c;</l>
 <l name="e">&#x044d;&#x042d;</l>
 <l name="ju">&#x044e;&#x042e;</l>
 <l name="ja">&#x044f;&#x042f;</l>
</lingvo>

<!-- kimra -->
<lingvo lng="cy" kreu-regulojn="jes" klaso="de.steloj.respiro.WelshCollator">
 <l name="a">a,A</l>
 <l name="b">b,B</l>
 <l name="c" minus="ch">c,C</l>
 <l name="ch" n="2">ch,cH,Ch,CH</l>
 <l name="d">d,D</l>
 <l name="e">e,E</l>
 <l name="f" minus="ff">f,F</l>
 <l name="ff" n="2">ff,fF,Ff,FF</l>
 <l name="g">g,G</l>
 <l name="h">h,H</l>
 <l name="i">i,I</l>
 <l name="j">j,J</l>
 <l name="l" minus="ll">l,L</l>
 <l name="ll" n="2">ll,lL,Ll,LL</l>
 <l name="m">m,M</l>
 <l name="n">n,N</l>
 <l name="o">o,O</l>
 <l name="p" minus="ph">p,P</l>
 <l name="ph" n="2">ph,pH,Ph,PH</l>
 <l name="r" minus="rh">r,R</l>
 <l name="rh" n="2">rh,rH,Rh,RH</l>
 <l name="s">s,S</l>
 <l name="t" minus="th">t,T</l>
 <l name="th" n="2">th,tH,Th,TH</l>
 <l name="u">u,U</l>
 <l name="w">w,W,&#x1e83;,&#x1e82;,&#x1e81;,&#x1e80;,&#x0175;,&#x0174;,&#x1e85;,&#x1e84;</l>
 <l name="y">y,Y,&#x1ef3;,&#x1ef2;,&#x0177;,&#x0176;,&#x0178;</l>
</lingvo>

<!-- dana -->
<lingvo lng="da">
 <l name="a">aA</l>
 <l name="b">bB</l>
 <l name="c">cC</l>
 <l name="d">dD</l>
 <l name="e">eE</l>
 <l name="f">fF</l>
 <l name="g">gG</l>
 <l name="h">hH</l>
 <l name="i">iI</l>
 <l name="j">jJ</l>
 <l name="k">kK</l>
 <l name="l">lL</l>
 <l name="m">mM</l>
 <l name="n">nN</l>
 <l name="o">oO</l>
 <l name="p">pP</l>
 <l name="q">qQ</l>
 <l name="r">rR</l>
 <l name="s">sS</l>
 <l name="t">tT</l>
 <l name="u">uU</l>
 <l name="v">vV</l>
 <l name="w">wW</l>
 <l name="x">xX</l>
 <l name="y">yY</l>
 <l name="z">zZ</l>
 <l name="ae">&#x00e6;&#x00c6;</l>
 <l name="oe">&#x00f8;&#x00d8;</l>
 <l name="aa">&#x00e5;&#x00c5;</l>
</lingvo>

<!-- germana -->
<lingvo lng="de">
 <l name="a">a,A,ä,Ä</l>
 <l name="b">b,B</l>
 <l name="c">c,C</l>
 <l name="d">d,D</l>
 <l name="e">e,E</l>
 <l name="f">f,F</l>
 <l name="g">g,G</l>
 <l name="h">h,H</l>
 <l name="i">i,I</l>
 <l name="j">j,J</l>
 <l name="k">k,K</l>
 <l name="l">l,L</l>
 <l name="m">m,M</l>
 <l name="n">n,N</l>
 <l name="o">o,O,ö,Ö</l>
 <l name="p">p,P</l>
 <l name="q">q,Q</l>
 <l name="r">r,R</l>
 <l name="s">s,S,ß</l>
 <l name="t">t,T</l>
 <l name="u">u,U,ü,Ü</l>
 <l name="v">v,V</l>
 <l name="w">w,W</l>
 <l name="x">x,X</l>
 <l name="y">y,Y</l>
 <l name="z">z,Z</l>
</lingvo>

<!-- germana -->
<!-- lingvo lng="de">
 <l name="a">a,A</l>
 <l name="b">b,B</l>
 <l name="c">c,C</l>
 <l name="d">d,D</l>
 <l name="e">e,E</l>
 <l name="f">f,F</l>
 <l name="g">g,G</l>
 <l name="h">h,H</l>
 <l name="i">i,I</l>
 <l name="j">j,J</l>
 <l name="k">k,K</l>
 <l name="l">l,L</l>
 <l name="m">m,M</l>
 <l name="n">n,N</l>
 <l name="o">o,O</l>
 <l name="p">p,P</l>
 <l name="q">q,Q</l>
 <l name="r">r,R</l>
 <l name="s">s,S,ß</l>
 <l name="t">t,T</l>
 <l name="u">u,U</l>
 <l name="v">v,V</l>
 <l name="w">w,W</l>
 <l name="x">x,X</l>
 <l name="y">y,Y</l>
 <l name="z">z,Z</l>
 <r>ae;&#x00e4;</r>
 <r>AE;&#x00c4;</r>
 <r>oe;&#x00f6;</r>
 <r>OE;&#x00d6;</r>
 <r>ue;&#x00fc;</r>
 <r>UE;&#x00dc;</r>
</lingvo -->

<!-- greka -->
<lingvo lng="el">
 <l name="a">&#x03b1;&#x0391;&#x03ac;&#x0386;</l>
 <l name="b">&#x03b2;&#x0392;</l>
 <l name="g">&#x03b3;&#x0393;</l>
 <l name="d">&#x03b4;&#x0394;</l>
 <l name="e">&#x03b5;&#x0395;&#x03ad;&#x0388;</l>
 <l name="z">&#x03b6;&#x0396;</l>
 <l name="h">&#x03b7;&#x0397;&#x03ae;&#x0389;</l>
 <l name="th">&#x03b8;&#x0398;</l>
 <l name="j">&#x03b9;&#x0399;&#x03af;&#x038a;&#x03ca;&#x03aa;&#x0390;</l>
 <l name="k">&#x03ba;&#x039a;</l>
 <l name="l">&#x03bb;&#x039b;</l>
 <l name="m">&#x03bc;&#x039c;</l>
 <l name="n">&#x03bd;&#x039d;</l>
 <l name="x">&#x03be;&#x039e;</l>
 <l name="o">&#x03bf;&#x039f;&#x03cc;&#x038c;</l>
 <l name="p">&#x03c0;&#x03a0;</l>
 <l name="r">&#x03c1;&#x03a1;</l>
 <l name="s">&#x03c3;&#x03a3;&#x03c2;</l>
 <l name="t">&#x03c4;&#x03a4;</l>
 <l name="y">&#x03c5;&#x03a5;&#x03cd;&#x038e;&#x03cb;&#x03ab;&#x03b0;</l>
 <l name="f">&#x03c6;&#x03a6;</l>
 <l name="ch">&#x03c7;&#x03a7;</l>
 <l name="ps">&#x03c8;&#x03a8;</l>
 <l name="om">&#x03c9;&#x03a9;&#x03ce;&#x038f;</l>
</lingvo>

<!-- angla -->
<lingvo lng="en">
 <l name="a">aA</l>
 <l name="b">bB</l>